### ISSUE TITLE
Cannot seem to get it work on neovim and tmux

### ISSUE THREAD

**Issue by EdmundsEcho** [roxma/vim-tmux-clipboard#13]
Hello - Thank you for this useful plugin.  I hope that I'm not missing anything obvious.  This is what I did:

1. installed the plugin on both nvim configurations (client and ssh host)
2. commented out the `set -g focus-events on` register I was using (tried with and without)
3. fire up tmux on my local machine
4. create two panes using tmux: one local, one ssh connected to the remote machine
5. open nvim in each pane
6. yank a line in one pane to see if I can then paste it into the second pane...
... to no avail.

I can copy text from one to the other using tmux `[` routine... but of course that is messy and thus a pain point I'm hoping this plugin will solve.

Am I doing anything wrong in how I have presented the workflow?

PS: I'm using the latest nvim and tmux.

\- E

**Comment by roxma** [comment]
> create two panes using tmux: one local, one ssh connected to the remote machine

This plugin only works for local nvim

It cannot sync the tmux clipboard to nvim on remote machine.

**Comment by EdmundsEcho** [comment]
Thank you for letting me know.  I'm not sure how I was given that impression.  All the best,  - E
