### ISSUE TITLE
Documentation on how to use under neovim

### ISSUE THREAD

**Issue by Frefreak** [roxma/vim-tmux-clipboard#2]
I just spent about half an hour figuring out how to use it under neovim, and it's working great right now. But based on my experience it seems the documentation can be improved a little bit? In my environment

- don't need to install `vim-tmux-focus-events` when using neovim. Its README even states its not working with neovim. The [requirement](https://github.com/roxma/vim-tmux-clipboard#requirements) section seems misleading.
- do need to add `set -g focus-events on` to `.tmux.conf` or the `FocusGained` and `FocusLost` events don't fire

Maybe this can save new users some time. Thank you for this useful plugin!

**Comment by roxma** [comment]
OK, thanks!

**Comment by bitozoid** [comment]
Btw, make sure you run a recent version of neovim. Version 0.1.0 does not work.
